version: '2'
services:
    szkatulka-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/szkatulka/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=szkatulka
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
